source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubygems"
gem "json"
gem "net/http"
gem "poke-api-v2"
gem "rmagick"
gem "ascii-image"
gem "colorize"
gem "tty-prompt"
gem "tty-table"
gem "paint"