# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "rspec"
gem "json"
gem "poke-api-v2"
gem "rmagick"
gem "ascii-image"
gem "colorize"
gem "tty-prompt"
gem "tty-table"
gem "paint"
